name: Publish Chrome Extension

on:
  push:
    branches:
      - main  # Change to your default branch name if different

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Pack the Chrome Extension into a ZIP file
    - name: Pack Chrome Extension
      run: |
        mkdir -p build
        zip -r build/extension.zip * -x "*.git*" "node_modules/*" ".github/*" "build/*"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension.zip
        path: build/extension.zip

    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'publish'  # one of: upload, publish, testers
        client_id: ${{ secrets.CLIENT }}
        client_secret: ${{ secrets.SECRET }}
        refresh_token: ${{ secrets.TOKEN }}
        extension_id: 'emfeiimnpfdlnppacfklndigkpkkmbpn' 
        zip_file: 'build/extension.zip'